### ISSUE TITLE
 Error reported during reasoning：_Map_base::at

### ISSUE THREAD

**Issue by chensheng-code** [MStypulkowski/diffused-heads#13]
Error reported during reasoning：_Map_base::at

 File "/home/diffusion.py", line 42, in sample
    sample_frame = self.sample_loop(xT[:, i].to(x_cond.device), x_cond, motion_frames, audio_emb[:, audio_ids])
  File "/home/diffusion.py", line 53, in sample_loop
    nn_out = self.nn_backbone(xt, timesteps, x_cond, motion_frames=motion_frames, audio_emb=audio_emb)
  File "/env3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: _Map_base::at

**Comment by wangryhen** [comment]
> Error reported during reasoning：_Map_base::at
> 
> File "/home/diffusion.py", line 42, in sample sample_frame = self.sample_loop(xT[:, i].to(x_cond.device), x_cond, motion_frames, audio_emb[:, audio_ids]) File "/home/diffusion.py", line 53, in sample_loop nn_out = self.nn_backbone(xt, timesteps, x_cond, motion_frames=motion_frames, audio_emb=audio_emb) File "/env3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) RuntimeError: _Map_base::at

Hello, I also encountered the same problem, have you solved it?

**Comment by chaoxxc** [comment]
hello, have anyone solved this problem?

**Comment by Wangman1** [comment]
您好，请问解决了吗

**Comment by YifengMa9** [comment]
As described in #8, the problem is solved when I change the pytorch version to 12.1
