### ISSUE TITLE
About the released date of training script

### ISSUE THREAD

**Issue by kaiw7** [MStypulkowski/diffused-heads#21]
Hi, when do you plan to release your training script? Thank you very much.

**Comment by johndpope** [comment]
I think I can get Claude3 to spit this out - give me a few days. 
should be able to just upload the paper - and all the respective code. maybe a schema dump of checkpoint - but presumably its' just a vanillla stable diffusion.
I'm attempting to recreate the Emote paper - https://github.com/johndpope/emote-hack
and I'll need this training code.
