### ISSUE TITLE
Checkpoint 

### ISSUE THREAD

**Issue by pranav-ap** [MStypulkowski/diffused-heads#23]
Why does the Training branch README say that no checkpoints are provided?
Can't we use the checkpoint given in the Sampling section.

Thanks

**Comment by MStypulkowski** [comment]
Checkpoints from the demo are scripted using torchscript. I'm not sure if they are suitable for training but you are free to try.

In any case, I updated README in the training branch with a link to a non-scripted CREMA checkpoint.
