### ISSUE TITLE
about train script

### ISSUE THREAD

**Issue by zhang-haojie** [MStypulkowski/diffused-heads#25]
Dear auther, how to set param `landmarks` and `audio_emb_dir` and  their corresponding data? Could you provide more information about them?

**Comment by johndpope** [comment]
you may find AniPortrait more relevant - they enhanced MediaPipe lip detection - and landmark detection is SOTA.
https://github.com/Zejun-Yang/AniPortrait/blob/cb86caa741d6ab1e119ea7ac2554eb28aabc631b/src/utils/face_landmark.py#L123

**Comment by MStypulkowski** [comment]
For `landmarks` we used [face-alignment](https://github.com/1adrianb/face-alignment). But feel free to use anything for that. 

`audio_emb_dir` is a directory containing audio embeddings. The folder structure should be the same as data's (as indicated by file list). You can find information on how to compute them in [README](https://github.com/MStypulkowski/diffused-heads/tree/train?tab=readme-ov-file#audio-embeddings).

**Comment by zhang-haojie** [comment]
The `landmarks` is 3D facial landmarks or 2D facial landmarks? Thank you

**Comment by MStypulkowski** [comment]
They are 2D.
