### ISSUE TITLE
The difference of checkpoint in the main and train branches

### ISSUE THREAD

**Issue by Hanbo-Cheng** [MStypulkowski/diffused-heads#27]
I notice that the checkpoint for CREMA in the main and train branches have different sizes (the checkpoint in the train branch is much larger). I want to confirm whether these two checkpoints share the same performance.

**Comment by sanjay-cloud** [comment]
How to resolve this 
RuntimeError: Distributed package doesn't have NCCL built in
I am using torch                  2.3.0+cu118

**Comment by MStypulkowski** [comment]
Yes, they should

**Comment by johndpope** [comment]
@MStypulkowski - are you familiar with Megaportraits paper? I attempted to rebuild it - but can't get it to boot up / cycle in training - I think some dimensiones are off. Maybe you could take a look if youre interested ?
https://github.com/johndpope/MegaPortrait-hack
Microsoft released VASA paper the other week that builds off this. 
https://github.com/johndpope/vasa-1-hack
https://www.microsoft.com/en-us/research/project/vasa-1/
The resenet structure helps achieve very high /reatlime FPS
