### ISSUE TITLE
ValueError: The provided filename /checkpoints/crema_script.pt does not exist

### ISSUE THREAD

**Issue by semihhdemirel** [MStypulkowski/diffused-heads#9]
raise ValueError("The provided filename {} does not exist".format(f))  # type: ignore[str-bytes-safe]
ValueError: The provided filename /checkpoints/crema_script.pt does not exist

The model could not be imported using the command "unet = torch.jit.load(args.checkpoint)" in sample.py(line 15) even though the file path exists.

**Comment by semihhdemirel** [comment]
@kormalev I tried your suggestion. But i encountered with the same error.
    raise ValueError("The provided filename {} does not exist".format(f))  # type: ignore[str-bytes-safe]
ValueError: The provided filename ./checkpoints/crema_script.pt does not exist

**Comment by MStypulkowski** [comment]
@semihhdemirel Try to use an absolute path, i.e. `/full/path/to/folder/with/checkpoints/crema_script.pt`

**Comment by semihhdemirel** [comment]
@MStypulkowski @hoalarious I tried the command "!python sample.py hydra.job.chdir=False", then it worked
